# Generated by Django 3.1.1 on 2020-09-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listings',
        ),
        migrations.AddField(
            model_name='comment',
            name='listings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
