# Generated by Django 3.1.1 on 2020-10-01 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200930_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'get_latest_by': 'id'},
        ),
    ]
