# Generated by Django 3.1.1 on 2020-10-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200930_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
